CREATE DATABASE MLS
GO

CREATE TABLE USERS(
	ID				INT IDENTITY
,	FIRST_NAME		VARCHAR(50)
,	LAST_NAME		VARCHAR(100)
,	USER_EMAIL		VARCHAR(200)
,	USER_PASSWORD	VARCHAR(200)
,	USER_ADMIN		BIT
,	CONSTRAINT PK_USERS PRIMARY KEY (ID)
,	CONSTRAINT UQ_EMAIL UNIQUE (USER_EMAIL)
)
GO

DROP TABLE IF EXISTS SCHEDULE
CREATE TABLE SCHEDULE(
	ID				INT IDENTITY
,	SCHEDULE_DATE	DATE NOT NULL
,	F_TEAM_NAME		VARCHAR(100) NOT NULL
,	S_TEAM_NAME		VARCHAR(100) NOT NULL
,	SCHEDULE_TIME	TIME(0)
,	SCORE			VARCHAR(10)
,	CONSTRAINT PK_SCHEDULE PRIMARY KEY (ID)
,	CONSTRAINT UQ_SCHEDULE UNIQUE (SCHEDULE_DATE, F_TEAM_NAME, S_TEAM_NAME)
)
GO

INSERT INTO USERS VALUES ('Armando', 'Defendi Rossi', 'armandorossi@hotmail.com', 'test', 1)

SELECT * FROM USERS

SELECT * FROM SCHEDULE (NOLOCK)

TRUNCATE TABLE SCHEDULE