USE u842004852_mlsproject_db;

CREATE TABLE USERS(
	ID				INT PRIMARY KEY AUTO_INCREMENT
,	FIRST_NAME		VARCHAR(50)
,	LAST_NAME		VARCHAR(100)
,	USER_EMAIL		VARCHAR(200)
,	USER_PASSWORD	VARCHAR(200)
,	USER_ADMIN		BIT
,	USER_STATUS		BIT
,	UNIQUE (USER_EMAIL)
);

CREATE TABLE SCHEDULE(
	ID				INT PRIMARY KEY AUTO_INCREMENT
,	SCHEDULE_DATE	DATE NOT NULL
,	F_TEAM_NAME		VARCHAR(100) NOT NULL
,	S_TEAM_NAME		VARCHAR(100) NOT NULL
,	SCHEDULE_TIME	TIME(0)
,	SCORE			VARCHAR(10)
,	RESULT			VARCHAR(100) GENERATED ALWAYS AS (IF(SCORE IS NULL, NULL, IF(SUBSTRING_INDEX(SCORE, ':', 1) > SUBSTRING_INDEX(REVERSE(SCORE), ':', 1), F_TEAM_NAME, IF(SUBSTRING_INDEX(SCORE, ':', 1) = SUBSTRING_INDEX(REVERSE(SCORE), ':', 1), 'Draw', S_TEAM_NAME))))
,	UNIQUE (SCHEDULE_DATE, F_TEAM_NAME, S_TEAM_NAME)
);

CREATE TABLE TEAMS(
	TEAM_ID			INT PRIMARY KEY AUTO_INCREMENT
,	TEAM_NAME		VARCHAR(50) NOT NULL
,	TEAM_SHORT_NAME	VARCHAR(50) NULL
,	TEAM_ESPN		VARCHAR(50) NULL
,	TEAM_ML			VARCHAR(50) NULL
,	UNIQUE (TEAM_NAME)
);

CREATE TABLE STANDINGS(
	COMPETITION_YEAR	INT
,	COMPETITION_TYPE	VARCHAR(30) NOT NULL
,	TEAM_NAME			VARCHAR(30) NOT NULL
,	TOTAL_POINTS		INT NOT NULL
,	POINTS_PER_GAME		FLOAT NOT NULL
,	TOTAL_MATCHES		INT NOT NULL
,	TOTAL_WINS			INT NOT NULL
,	TOTAL_LOSSES		INT NOT NULL
,	TOTAL_DRAWS			INT NOT NULL
,	TOTAL_GOALS			INT NOT NULL
,	GOALS_CONCEDED		INT NOT NULL
,	GOALS_DIFFERENCE	INT NOT NULL
,	HOME_RECORD			VARCHAR(10) NOT NULL
,	AWAY_RECORD			VARCHAR(10) NOT NULL
,	PRIMARY KEY	(COMPETITION_YEAR, COMPETITION_TYPE, TEAM_NAME)
);

CREATE TABLE RANKBASE (
	GENERALKEY	INT AUTO_INCREMENT PRIMARY KEY
,	RK			INT NOT NULL
,	TEAM_NAME	VARCHAR(50) NOT NULL
,	MP			INT
,	W			INT
,	D			INT
,	L			INT
,	GF			INT
,	GA			INT
,	GD			INT
,	PTS			INT
,	PTS_MP		FLOAT
,	XG			FLOAT
,	XGA			FLOAT
,	XGD			FLOAT
,	XGD_90		FLOAT
,	NOTES		VARCHAR(60)
,	CONFERENCE	VARCHAR(50)
,	SEASON		INT NOT NULL
);

CREATE TABLE DETAILSBASE (
	GENERALKEY		INT AUTO_INCREMENT PRIMARY KEY
,	TEAM_NAME		VARCHAR(50) NOT NULL
,	GAME_DATE		DATE NOT NULL
,	GAME_TIME		TIME NOT NULL
,	COMP			VARCHAR(50)
,	SEASON_ROUND	VARCHAR(100)
,	WEEK_DAY		VARCHAR(20)
,	TEAM_VENUE		VARCHAR(20)
,	GAME_RESULT		VARCHAR(5)
,	GF				INT
,	GA				INT
,	OPPONENT		VARCHAR(50)
,	XG				FLOAT
,	XGA				FLOAT
,	POSS			INT
,	ATTENDANCE		FLOAT
,	CAPTAIN			VARCHAR(50)
,	FORMATION		VARCHAR(50)
,	REFEREE			VARCHAR(50)
,	NOTES			VARCHAR(50)
,	SEASON			INT
);

CREATE TABLE GAMEDETAILS (
    GENERALKEY	INT AUTO_INCREMENT PRIMARY KEY
,	GAME_DATE	DATE NOT NULL
,	GAME_TIME	TIME NOT NULL
,	WEEK_DAY	VARCHAR(20)
,	TEAM_AWAY	VARCHAR(50)
,	TEAM_HOME	VARCHAR(50)
,	RESULT_GAME	VARCHAR(1)
,	SEASON		INT NOT NULL
);

CREATE TABLE RANKINGSTANDARDTEAMNAMES (
    GENERALKEY		INT AUTO_INCREMENT PRIMARY KEY
,	RK				INT NOT NULL
,	TEAM_NAME		VARCHAR(50) NOT NULL
,	MP				INT
,	W				INT
,	D				INT
,	L				INT
,	GF				INT
,	GA				INT
,	GD				INT
,	PTS				INT
,	PTS_MP			FLOAT
,	XG				FLOAT
,	XGA				FLOAT
,	XGD				FLOAT
,	XGD_90			FLOAT
,	NOTES			VARCHAR(60)
,	CONFERENCE		VARCHAR(50)
,	SEASON			INT NOT NULL
);

CREATE TABLE MATCHDETAILSFULL (
    GENERALKEY		INT AUTO_INCREMENT PRIMARY KEY
,	GAME_DATE		DATE NOT NULL
,	GAME_TIME		TIME NOT NULL
,	WEEK_DAY		VARCHAR(20)
,	TEAM_AWAY		VARCHAR(50)
,	TEAM_HOME		VARCHAR(50)
,	RESULT_GAME		VARCHAR(1)
,	SEASON			INT NOT NULL
,	SEASON_BEFORE	INT NOT NULL
,	HOME_SB_RK		FLOAT
,	HOME_SB_PTS_MP	FLOAT
,	HOME_SB_W_MP	FLOAT
,	HOME_SB_D_MP	FLOAT
,	HOME_SB_L_MP	FLOAT
,	HOME_SB_GD_MP	FLOAT
,	AWAY_SB_RK		FLOAT
,	AWAY_SB_PTS_MP	FLOAT
,	AWAY_SB_W_MP	FLOAT
,	AWAY_SB_D_MP	FLOAT
,	AWAY_SB_L_MP	FLOAT
,	AWAY_SB_GD_MP	FLOAT
);