CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(100),
  USER_EMAIL VARCHAR(200),
  USER_PASSWORD VARCHAR(200),
  USER_ADMIN BOOLEAN,
  PRIMARY KEY (ID),
  UNIQUE (USER_EMAIL)
);

DROP TABLE IF EXISTS SCHEDULE;
CREATE TABLE SCHEDULE (
  ID INT NOT NULL AUTO_INCREMENT,
  SCHEDULE_DATE DATE NOT NULL,
  F_TEAM_NAME VARCHAR(100) NOT NULL,
  S_TEAM_NAME VARCHAR(100) NOT NULL,
  SCHEDULE_TIME TIME,
  SCORE VARCHAR(10),
  PRIMARY KEY (ID),
  UNIQUE (SCHEDULE_DATE, F_TEAM_NAME, S_TEAM_NAME)
);

